# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/complex_multiplier_18_18_ip/complex_multiplier_18_18_ip.xci
# IP: The module: 'complex_multiplier_18_18_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/complex_multiplier_18_18_ip/complex_multiplier_18_18_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'complex_multiplier_18_18_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/complex_multiplier_18_18_ip/complex_multiplier_18_18_ip.xci
# IP: The module: 'complex_multiplier_18_18_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/complex_multiplier_18_18_ip/complex_multiplier_18_18_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'complex_multiplier_18_18_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
