# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dpram_1024_ip/dpram_1024_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpram_1024_ip || ORIG_REF_NAME==dpram_1024_ip}]
