# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045fbg676-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.cache/wt [current_project]
set_property parent.project_path F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{f:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/User Repository}} [current_project]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/spram_72_64_ip_synth_1/spram_72_64_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/spram_72_64_ip_synth_1/spram_72_64_ip.dcp]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/spram_36_64_ip_synth_1/spram_36_64_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/spram_36_64_ip_synth_1/spram_36_64_ip.dcp]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/complex_multiplier_18_18_ip_synth_1/complex_multiplier_18_18_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/complex_multiplier_18_18_ip_synth_1/complex_multiplier_18_18_ip.dcp]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/multiplier_42_42_ip_synth_1/multiplier_42_42_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/multiplier_42_42_ip_synth_1/multiplier_42_42_ip.dcp]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/dpram_36_1024_ip_synth_1/dpram_36_1024_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/dpram_36_1024_ip_synth_1/dpram_36_1024_ip.dcp]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/spram_144_32_ip_synth_1/spram_144_32_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/spram_144_32_ip_synth_1/spram_144_32_ip.dcp]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/spram_144_512_ip_synth_1/spram_144_512_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/spram_144_512_ip_synth_1/spram_144_512_ip.dcp]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/complex_abs_power2_42_ip_synth_1/complex_abs_power2_42_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/complex_abs_power2_42_ip_synth_1/complex_abs_power2_42_ip.dcp]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/complex_abs_power2_18_ip_synth_1/complex_abs_power2_18_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/complex_abs_power2_18_ip_synth_1/complex_abs_power2_18_ip.dcp]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/complex_abs_power2_35_1dsp_ip_synth_1/complex_abs_power2_35_1dsp_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/complex_abs_power2_35_1dsp_ip_synth_1/complex_abs_power2_35_1dsp_ip.dcp]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/multiplier_35_1dsp_ip_synth_1/multiplier_35_1dsp_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/multiplier_35_1dsp_ip_synth_1/multiplier_35_1dsp_ip.dcp]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/multiplier_69_18_1dsp_ip_synth_1/multiplier_69_18_1dsp_ip.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/multiplier_69_18_1dsp_ip_synth_1/multiplier_69_18_1dsp_ip.dcp]
read_verilog -library xil_defaultlib {
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/tools/axis_interface_fifo.v
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/coarse_sync/tar.v
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/coarse_sync/psi.v
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/coarse_sync/phi.v
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/fine_sync/lambda.v
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/fine_sync/peak_search.v
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/data_dpram/data_dpram.v
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/coarse_sync/coarse_sync.v
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/fine_sync/fine_sync.v
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/ofdm_syn.v
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/test_ofdm_syn.v
}
synth_design -top test_ofdm_syn -part xc7z045fbg676-3
write_checkpoint -noxdef test_ofdm_syn.dcp
catch { report_utilization -file test_ofdm_syn_utilization_synth.rpt -pb test_ofdm_syn_utilization_synth.pb }
