# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/modeltech64_10.4/win64
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045fbg676-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.cache/wt [current_project]
set_property parent.project_path E:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet E:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.runs/spram_103_32_ip_synth_1/spram_103_32_ip.dcp
set_property used_in_implementation false [get_files E:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.runs/spram_103_32_ip_synth_1/spram_103_32_ip.dcp]
add_files -quiet E:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.runs/multiplier_ip_42_42_synth_1/multiplier_ip_42_42.dcp
set_property used_in_implementation false [get_files E:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.runs/multiplier_ip_42_42_synth_1/multiplier_ip_42_42.dcp]
read_verilog -library xil_defaultlib {
  E:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/tools/complex_abs_power2_42.v
  E:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/operator/tar_operator.v
  E:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/operator/test_tar_operator.v
}
synth_design -top test_tar_operator -part xc7z045fbg676-3
write_checkpoint -noxdef test_tar_operator.dcp
catch { report_utilization -file test_tar_operator_utilization_synth.rpt -pb test_tar_operator_utilization_synth.pb }
