# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045fbg676-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.cache/wt [current_project]
set_property parent.project_path F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/complex_multiplier_ip_16_16_synth_1/complex_multiplier_ip_16_16.dcp
set_property used_in_implementation false [get_files F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.runs/complex_multiplier_ip_16_16_synth_1/complex_multiplier_ip_16_16.dcp]
read_verilog -library xil_defaultlib {
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/operator/psi_operator.v
  F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/code/operator/test_psi_operator.v
}
synth_design -top test_psi_operator -part xc7z045fbg676-3
write_checkpoint -noxdef test_psi_operator.dcp
catch { report_utilization -file test_psi_operator_utilization_synth.rpt -pb test_psi_operator_utilization_synth.pb }
