# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/multiplier_ip_42_42/multiplier_ip_42_42.xci
# IP: The module: 'multiplier_ip_42_42' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/multiplier_ip_42_42/multiplier_ip_42_42_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier_ip_42_42'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/multiplier_ip_42_42/multiplier_ip_42_42.xci
# IP: The module: 'multiplier_ip_42_42' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/multiplier_ip_42_42/multiplier_ip_42_42_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier_ip_42_42'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
