# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/spram_72_64_ip/spram_72_64_ip.xci
# IP: The module: 'spram_72_64_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/spram_72_64_ip/spram_72_64_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spram_72_64_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: F:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/spram_72_64_ip/spram_72_64_ip.xci
# IP: The module: 'spram_72_64_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/jiaweiwei/Project/OFDM_Synchronization/OFDM_Synchronization/OFDM_Synchronization.srcs/sources_1/ip/spram_72_64_ip/spram_72_64_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spram_72_64_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
